### ISSUE TITLE
Spring management endpoints exposure compatibility

### ISSUE THREAD

**Issue by ddieruf** [SteeltoeOSS/Steeltoe#498]
## Describe the solution you'd like
When I am using config first approach, all app settings are embedded in a yaml configurations file. To tell my application to expose all actuators I need to "include: *". In Steeltoe this done by
``` yaml
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
```

but in Spring this done by

``` yaml
management:
  endpoints:
    web:
      exposure:
        include: '*'
```

Ideally, Steeltoe could support the Spring way of exposing management endpoints.

## Additional context
Here is the yaml I discovered the differences:
https://github.com/steeltoeoss-incubator/spring-petclinic-microservices-config/blob/master/application.yml
