### ISSUE TITLE
Health actuator path in Eureka client

### ISSUE THREAD

**Issue by ddieruf** [SteeltoeOSS/Steeltoe#499]
## Describe the solution you'd like
When I am using Eureka for discovery and have turned on management endpoints (like health), my Eureka client should follow management endpoints defaults. Ie: `/actuator`

Currently, to get Eureka to see my management endpoints and report my app as healthy I have to add the config

``` yaml
eureka:
  instance:
    HealthCheckUrlPath: /actuator/health
    HomePageUrlPath: /actuator
```

Ideally, the Eureka client could be smart enough to figure this out itself.

## Additional context
Here is the yaml I discovered the differences:
https://github.com/steeltoeoss-incubator/spring-petclinic-microservices-config/blob/master/application.yml
