### ISSUE TITLE
Kubernetes ConfigMap file parsing

### ISSUE THREAD

**Issue by DaviGia** [SteeltoeOSS/Steeltoe#639]
## Describe problem
If I declare a file within a ConfigMap the `KubernetesConfigProvider` reads it as a single property and does not evaluate the value as json. Spring provides a similar functionality where you can specify a yaml or properties file within a ConfigMap and it will be parsed correctly ([link](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource)).

## Describe solution
I would like to be able to specify a file within ConfigMap and have all the content parsed correctly.

For example, provided the following ConfigMap:

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  appsettings.json: |
    {
      "Test0": "Value0",
      "Test1": [
         {
            "Test2": "Value1"
         }
      ]
    }
```

the `KubernetesConfigProvider` should translate it in the following configuration properties:

|Key|Value|
|--|--|
|Test0|Value0|
|Test1:0:Test2|Value1|

If possible, it would be nice allow the provider to parse not only json but even yaml. 

## Describe alternatives
At the moment I will fallback into using a simple map in the ConfigMap.

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
data:
  "Test0": "Value0"
  "Test1:0:Test2": "Value1"
```
