### ISSUE TITLE
Cannot assign requested address exception when registering client to existing Eureka container

### ISSUE THREAD

**Issue by Ed87** [SteeltoeOSS/Steeltoe#731]
I have an existing  Eureka  container  and I have already successfully registered one microservice as a client . Now when I try to register a second microservice I am getting an error  _Cannot assign requested address_  as in the log below :

```
paymentsapi_1  | fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
paymentsapi_1  |       DoGetApplicationsAsync Failed
paymentsapi_1  | System.Net.Http.HttpRequestException: Cannot assign requested address
paymentsapi_1  |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
paymentsapi_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
paymentsapi_1  |    --- End of inner exception stack trace ---
paymentsapi_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
paymentsapi_1  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
paymentsapi_1  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)paymentsapi_1  |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)     
paymentsapi_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
paymentsapi_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
paymentsapi_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
paymentsapi_1  |    at Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient.DoGetApplicationsAsync(String path, ISet`1 regions)
paymentsapi_1  | fail: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
paymentsapi_1  |       FetchRegistry Failed
```

As a check I have tried to add the second microservice to the network where Eureka client is running as in docker-compose below but I am still getting same error:

```yaml
version: '3.4'
services:
  paymentsapi:
    build: .
    ports: 
      - "5040:5000"
    depends_on:
      - mysqldata
      
          
  mysqldata:
    image: mysql:5.7
    ports:
      - '33306:3306'
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: PaymentsDB
       MYSQL_USER: xxxx
       MYSQL_PASSWORD: xxxx
    volumes:
       - dbdata:/var/lib/mysql
    
volumes:
    dbdata:

networks:
  default:
    external: true
    name: productsapi_default
```

appsettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "mysqlconnection": "server=mysqldata;port=3306;database=PaymentsDB;userid=xxxx;password=xxxx;",
    "SqlSvrConn": "Server=MACHINENAME\\GOLIDE;Database=PaymentsDB;Trusted_Connection=True;MultipleActiveResultSets=true;"
  },
  "spring": {
    "application": {
      "name": "PaymentService"
    }
  },
  "eureka": {
    "client": {
      "shouldRegisterWithEureka": true,
      "serviceUrl": "http://localhost:8761/eureka",
      "ValidateCertificates": false
    },
    "instance": {
      "appName": "PaymentService",
      "port": "5040",
      "hostName": "localhost"     
    }
  }
}
```

## Environment :
.Net Core 3.1
Steeltoe.Discovery.ClientCore 3.1.0
Docker Engine - Community Ver 20.10.6 + WSL2
