### ISSUE TITLE
Config Server client does not properly initialize lists when using profiles

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Steeltoe#801]
A working example exhibiting the behavior exists at https://github.com/ccheetham/spring-config-examples.

The example uses Steeltoe version 3.1.0.

In the example, the default config profile defines the following list of addresses:
```
addressbook:
  address:
    - line1: "123 Main St"
      line2: "Apt 4"
      city: "Any Town"
      state: "USA"
      zipcode: "98765"
    - line1: "456 Elm St"
      city: "Peoria"
      state: "IL"
      zipcode: "61601"
```

There is also a Development config profile which re-defines the list:
```
addressbook:
  address:
    - line1: 789 Nascent Ave
      line2: Bldg 678
      city: New Town
      state: USA
      zipcode: 45678
```

The Spring Boot client returns the following list:
```
{
    "addresses": [
        {
            "city": "New Town",
            "line1": "789 Nascent Ave",
            "line2": "Bldg 678",
            "state": "USA",
            "zipcode": "45678"
        }
    ]
}
```

The Steeltoe Config Server client returns the following list:
```
{
    "address": [
        {
            "city": "New Town",
            "line1": "789 Nascent Ave",
            "line2": "Bldg 678",
            "state": "USA",
            "zipcode": "45678"
        },
        {
            "city": "Peoria",
            "line1": "456 Elm St",
            "line2": null,
            "state": "IL",
            "zipcode": "61601"
        }
    ]
}
```

It appears the Steeltoe implementation is simply overwriting elements in the list rather than resetting the list prior to population.
